typography_spectrum: 0.7197891601826996
color:
  brandStrength: 0.5814404785633087
  lightness: 0.3894053774420172
  saturation: 0.11943295202217996
  rhythmicContrast: 0.43980501615442336
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
layout_spectrum: 0.3471159813925624
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b503839-3fe7-417f-930b-eca6e3d4ccd7.png
name: coffees
style: the-composer
navigation:
  - name: test
    id: 7d696ac1-808c-46a9-93d4-895298707f8c
    type: content
  - name: One Drop Coffee
    url: 'http://onedropcoffee.com/'
    type: external
  - name: test
    id: 6156e4f7-35e9-48f9-9c84-e4397c39fb99
    type: content
title: Coffee
description: I love coffee
